### ISSUE TITLE
[​GB18030]Publish a project with GB18030 encoded characters in the project name will meet error.

### ISSUE THREAD

**Issue by anhp** [aspnet/KRuntime#1023]
This bug  is tracking Dev14 issue # 1092241.

VS:ENU 14.0.22403.0 WPT
Machine is WNVM14241
Steps to reproduce:
1. First change the system locale to Chinese(Simplified,China).
 
The computer needs a restart.
2. Then start VS.
3. Create a new C# ASP.NET 5 Starter Web with GB18030 chars in the name called:GB18030Publish㐀㒣㕴
Then publish the site to file system or windows azure website will get an exception in the output window, and the project didn't display.

Log is here: 
System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.Security.Permissions.FileIOPermission.CheckIllegalCharacters(String[] str)
   at System.Security.Permissions.FileIOPermission.AddPathList(FileIOPermissionAccess access, AccessControlActions control, String[] pathListOrig, Boolean checkForDuplicates, Boolean needFullPath, Boolean copyPathList)
   at System.Security.Permissions.FileIOPermission..ctor(FileIOPermissionAccess access, String[] pathList, Boolean checkForDuplicates, Boolean needFullPath)
   at System.IO.Path.GetFullPath(String path)
   at Microsoft.Framework.PackageManager.Packing.PackManager.Normalize(String projectDir)
   at Microsoft.Framework.PackageManager.Packing.PackManager..ctor(IServiceProvider hostServices, PackOptions options)
   at Microsoft.Framework.PackageManager.Program.<>c__DisplayClass2.<Main>b__11()
   at Microsoft.Framework.Runtime.Common.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.Framework.PackageManager.Program.Main(String[] args)
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\Web\Microsoft.AspNet.Publishing.targets(105,5): Error MSB3073: The command "set path=C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Web Tools\External\grunt-cli;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Web Tools\External\bower;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Web Tools\External\npm;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Web Tools\External\git;%Path% 
 "C:\Users\fwtlaba\.kre\packages\kre-clr-x86.1.0.0-beta2-10739\bin\kpm.cmd" pack --runtime KRE-CLR-x86.1.0.0-beta2-10739 --out "C:\Users\fwtlaba\AppData\Local\Temp\AspNetPublish\GB18030Publish㐀㒣㕴-94" --wwwroot-out wwwroot --configuration Release --quiet" exited with code 1.

**Comment by wenhx** [comment]
你贴的中文怎么变成乱码了？ 用非ASCII字符做文件名不是个好习惯。

**Comment by Eilon** [comment]
Attempted translation:
> How do you Chinese garbled? Do filenames with non-ASCII characters is not a good habit.

**Comment by wenhx** [comment]
@Eilon yes, I think @anhp can read chinese, and I am trying test that is comment not supported chinese.

**Comment by anhp** [comment]
@wenhx,
I can't read Chinese!

**Comment by Praburaj** [comment]
This is a dup of https://github.com/aspnet/KRuntime/issues/1023.
