### ISSUE TITLE
System.InvalidOperationException: Failed to resolve the following dependencies for target framework 'Asp.NetCore,Version=v5.0'

### ISSUE THREAD

**Issue by brporter** [aspnet/KRuntime#1040]
Any project that I generate (I'm using Yeoman) that I then try and run under CoreCLR gives this message:
```
 System.InvalidOperationException: Failed to resolve the following dependencies for target framework 'Asp.NetCore,Version
=v5.0':
   Microsoft.Win32.Registry 4.0.0-beta-22231
   System.Collections 4.0.10-beta-22231
   System.Collections.Concurrent 4.0.0-beta-22231
   System.Console 4.0.0-beta-22231
   System.Diagnostics.Contracts 4.0.0-beta-22231
   System.Diagnostics.Debug 4.0.10-beta-22231
   System.Diagnostics.Tools 4.0.0-beta-22231
   System.Diagnostics.TraceSource 4.0.0-beta-22231
   System.Diagnostics.Tracing 4.0.10-beta-22231
   System.Globalization 4.0.10-beta-22231
   System.Globalization.Extensions 4.0.0-beta-22231
   System.IO 4.0.10-beta-22231
   System.IO.FileSystem 4.0.0-beta-22231
   System.Linq 4.0.0-beta-22231
   System.Linq.Expressions 4.0.0-beta-22231
   System.Net.Primitives 4.0.10-beta-22231
   System.Reflection 4.0.10-beta-22231
   System.Reflection.Extensions 4.0.0-beta-22231
   System.Reflection.TypeExtensions 4.0.0-beta-22231
   System.Resources.ResourceManager 4.0.0-beta-22231
   System.Runtime.Extensions 4.0.10-beta-22231
   System.Runtime.Handles 4.0.0-beta-22231
   System.Runtime.InteropServices 4.0.20-beta-22231
   System.Security.Claims 4.0.0-beta-22231
   System.Security.Cryptography.Encryption 4.0.0-beta-22231
   System.Security.Cryptography.Encryption.Aes 4.0.0-beta-22231
   System.Security.Cryptography.Hashing.Algorithms 4.0.0-beta-22231
   System.Security.Cryptography.RandomNumberGenerator 4.0.0-beta-22231
   System.Security.Cryptography.X509Certificates 4.0.0-beta-22231
   System.Security.Principal 4.0.0-beta-22231
   System.Security.Principal.Windows 4.0.0-beta-22231
   System.Text.Encoding 4.0.10-beta-22231
   System.Text.Encoding.Extensions 4.0.10-beta-22231
   System.Threading 4.0.0-beta-22231
   System.Threading.Tasks 4.0.10-beta-22231
   System.Threading.Thread 4.0.0-beta-22231
   System.Threading.ThreadPool 4.0.10-beta-22231
   System.Xml.XDocument 4.0.0-beta-22231

Searched Locations:
  C:\Projects\{name}\project.json
  C:\Users\brporter\.kpm\packages\{name}\{version}\{name}.nuspec

Try running 'kpm restore'.

   at Microsoft.Framework.Runtime.DefaultHost.GetEntryPoint(String applicationName)
   at Microsoft.Framework.ApplicationHost.Program.ExecuteMain(DefaultHost host, String applicationName, String[] args)
   at Microsoft.Framework.ApplicationHost.Program.Main(String[] args)
```

kpm restore doesn't seem to make a difference. 

Here is the list of runtimes I've got loaded on my machine.
```
Active Version     Runtime Architecture Location                        Alias
------ -------     ------- ------------ --------                        -----
       1.0.0-beta1 CLR     x86          C:\Users\brporter\.kre\packages
       1.0.0-beta1 CoreCLR amd64        C:\Program Files\KRE\packages
  *    1.0.0-beta1 CoreCLR x86          C:\Users\brporter\.kre\packages default
```

Running on CLR works.

**Comment by davidfowl** [comment]
Did you run kpm restore like the error says?

**Comment by brporter** [comment]
Of course. 

Took a second look, and I think the ASP.NET generator Yeoman must be out of date; the generated project.json referenced the wrong dependencies. Updated that, and it's working properly now.

**Comment by davidfowl** [comment]
Ok, file a bug on that then.
